#!/usr/bin/env bun
/**
 * Generate docs/, skills/ and mcp/ from flamingo.ts.
 *
 * These directories are checked in so they can be read on GitHub without running
 * anything, but a hand-maintained copy of a live surface goes stale within a
 * week. Generating them means the copy cannot drift, and `bun test` fails if the
 * checked-in files stop matching what the code produces.
 *
 *   bun run docs           regenerate
 *   bun run docs --check   fail if anything is out of date
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { Engine, SKILL_MD, MCP_INSTRUCTIONS, schemaDoc } from "../flamingo.ts";

const doc = schemaDoc();
const check = Bun.argv.includes("--check");
const stale: string[] = [];

function emit(path: string, body: string) {
  const full = join(import.meta.dir, "..", path);
  if (check) {
    if (!existsSync(full) || readFileSync(full, "utf8") !== body) stale.push(path);
    return;
  }
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body);
  console.log(`  ${path}`);
}

const GENERATED = "<!-- Generated by `bun run docs` from flamingo.ts. Do not edit by hand. -->\n\n";
const fence = (lang: string, body: string) => "```" + lang + "\n" + body + "\n```";

// ---------------------------------------------------------------- docs/cli.md
emit(
  "docs/cli.md",
  GENERATED +
    `# CLI reference\n\nflamingo ${doc.version} — ${doc.tagline}\n\n` +
    `## Commands\n\n| Command | Summary | Exit |\n| :-- | :-- | :-- |\n` +
    doc.commands.map((c) => `| \`${`flamingo ${c.name} ${c.args}`.trim()}\` | ${c.summary} | ${c.exits} |`).join("\n") +
    `\n\n` +
    doc.commands
      .map(
        (c) =>
          `## \`${`flamingo ${c.name} ${c.args}`.trim()}\`\n\n${c.summary}\n\n` +
          (c.flags.length ? `**Options:** ${c.flags.map((f) => `\`${f}\``).join(", ")}\n\n` : "") +
          `**Exit:** ${c.exits}\n\n` +
          fence("bash", c.examples.join("\n")),
      )
      .join("\n\n") +
    `\n\n## Exit codes\n\n| Code | Meaning |\n| :-- | :-- |\n` +
    Object.entries(doc.exitCodes).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n") +
    "\n",
);

// ---------------------------------------------------------- docs/mcp-tools.md
emit(
  "docs/mcp-tools.md",
  GENERATED +
    `# MCP tools\n\n${doc.tools.length} tools, served over stdio JSON-RPC by \`flamingo serve\`.\n\n` +
    `Backends: default \`${doc.backends.default}\`. These need \`--backend chrome\`: ` +
    doc.backends.chromeOnly.map((t) => `\`${t}\``).join(", ") +
    `.\n\n## Server instructions\n\nSent to every client on \`initialize\`:\n\n` +
    fence("text", MCP_INSTRUCTIONS) +
    `\n\n## Tools\n\n` +
    doc.tools
      .map((t) => `### \`${t.name}\`\n\n${t.description}\n\n` + fence("json", JSON.stringify(t.inputSchema, null, 2)))
      .join("\n\n") +
    "\n",
);

// ---------------------------------------------------------------- docs/api.md
// The method list comes from the runtime prototype, so it cannot drift from the
// code. Only the prose is read out of the source, and only from the JSDoc block
// immediately above each declaration.
const source = readFileSync(join(import.meta.dir, "..", "flamingo.ts"), "utf8");

const privateNames = new Set(
  [...source.matchAll(/\n\s+private\s+(?:readonly\s+|async\s+)*([a-zA-Z][a-zA-Z0-9]*)\s*[(<]/g)].map((m) => m[1]!),
);

function jsdocFor(name: string): string | null {
  const decl = new RegExp(`\\n  (?:async )?${name}\\s*[(<]`).exec(source);
  if (!decl) return null;
  const before = source.slice(Math.max(0, decl.index - 1200), decl.index);
  const open = before.lastIndexOf("/**");
  if (open < 0) return null;
  const close = before.indexOf("*/", open);
  // the block must sit immediately above the declaration, nothing in between
  if (close < 0 || /\S/.test(before.slice(close + 2))) return null;
  const text = before
    .slice(open + 3, close)
    .split("\n")
    .map((l) => l.replace(/^\s*\*\s?/, "").trim())
    .filter((l) => l && !l.startsWith("@"))
    .join(" ");
  // Several methods are numbered after the PRD ("2. Resize through viewports…");
  // taking the first sentence naively yields "2." and nothing else.
  const firstSentence = text.replace(/^\d+\.\s*/, "").split(/(?<=\.)\s/)[0]!.trim();
  return firstSentence || null;
}

const documented: Array<{ name: string; doc: string }> = [];
const undocumented: string[] = [];
for (const name of Object.getOwnPropertyNames(Engine.prototype).sort()) {
  if (name === "constructor" || privateNames.has(name)) continue;
  const descriptor = Object.getOwnPropertyDescriptor(Engine.prototype, name);
  if (!descriptor || typeof descriptor.value !== "function") continue;
  const doc = jsdocFor(name);
  if (doc) documented.push({ name, doc });
  else undocumented.push(name);
}

// A public method with no doc comment is a gap in the docs, not something to
// quietly omit — say so rather than shipping a table that looks complete.
if (undocumented.length) console.warn(`  ! undocumented public methods: ${undocumented.join(", ")}`);

emit(
  "docs/api.md",
  GENERATED +
    `# Library API\n\n` +
    fence("ts", `import { Engine } from "@ayuxy027/flamingo";\n\nawait using e = await Engine.open({ url: "http://localhost:3000" });\nconst step = await e.observe();`) +
    `\n\n${documented.length} public methods on \`Engine\`.\n\n| Method | What it does |\n| :-- | :-- |\n` +
    documented.map((m) => `| \`${m.name}\` | ${m.doc} |`).join("\n") +
    `\n\n## Also exported\n\n| Export | Purpose |\n| :-- | :-- |\n` +
    `| \`renderObservation(o)\` | Compact text form of an observation, ~74% fewer tokens than JSON |\n` +
    `| \`runMcpServer(opts)\` | Serve the MCP protocol on stdin/stdout |\n` +
    `| \`schemaDoc()\` | The machine-readable description of every command and tool |\n` +
    `| \`SKILL_MD\`, \`MCP_INSTRUCTIONS\` | The agent-facing guidance, as written by \`flamingo init\` |\n`,
);

// ------------------------------------------------------------------- skills/
emit("skills/flamingo/SKILL.md", SKILL_MD);

// ---------------------------------------------------------------------- mcp/
emit(
  "mcp/config.json",
  JSON.stringify({ mcpServers: { flamingo: { command: "bunx", args: ["flamingo", "serve"] } } }, null, 2) + "\n",
);
emit("mcp/tools.json", JSON.stringify(doc, null, 2) + "\n");

if (check) {
  if (stale.length) {
    console.error(`\n\x1b[31mout of date:\x1b[0m\n${stale.map((p) => "  " + p).join("\n")}\n\nRun \`bun run docs\`.\n`);
    process.exit(1);
  }
  console.log("docs, skills and mcp are up to date");
} else {
  console.log("\ngenerated from flamingo.ts");
}
