#!/usr/bin/env bun

import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { Engine, SKILL_MD, MCP_INSTRUCTIONS, schemaDoc } from "../flamingo.ts";

const doc = schemaDoc();
const check = Bun.argv.includes("--check");
const stale: string[] = [];

function emit(path: string, body: string) {
  const full = join(import.meta.dir, "..", path);
  if (check) {
    if (!existsSync(full) || readFileSync(full, "utf8") !== body) stale.push(path);
    return;
  }
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body);
  console.log(`  ${path}`);
}

const GENERATED = "<!-- Generated by `bun run docs` from flamingo.ts. Do not edit by hand. -->\n\n";
const fence = (lang: string, body: string) => "```" + lang + "\n" + body + "\n```";

emit(
  "docs/cli.md",
  GENERATED +
    `# CLI reference\n\nFlamingo ${doc.version} - ${doc.tagline}\n\n` +
    `## Commands\n\n| Command | Summary | Exit |\n| :-- | :-- | :-- |\n` +
    doc.commands.map((c) => `| \`${`flamingo ${c.name} ${c.args}`.trim()}\` | ${c.summary} | ${c.exits} |`).join("\n") +
    `\n\n` +
    doc.commands
      .map(
        (c) =>
          `## \`${`flamingo ${c.name} ${c.args}`.trim()}\`\n\n${c.summary}\n\n` +
          (c.flags.length ? `**Options:** ${c.flags.map((f) => `\`${f}\``).join(", ")}\n\n` : "") +
          `**Exit:** ${c.exits}\n\n` +
          fence("bash", c.examples.join("\n")),
      )
      .join("\n\n") +
    `\n\n## Exit codes\n\n| Code | Meaning |\n| :-- | :-- |\n` +
    Object.entries(doc.exitCodes).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n") +
    "\n",
);

emit(
  "docs/mcp-tools.md",
  GENERATED +
    `# MCP tools\n\n${doc.tools.length} tools, served over stdio JSON-RPC by \`flamingo serve\`.\n\n` +
    `Backends: default \`${doc.backends.default}\`. These need \`--backend chrome\`: ` +
    doc.backends.chromeOnly.map((t) => `\`${t}\``).join(", ") +
    `.\n\n## Server instructions\n\nSent to every client on \`initialize\`:\n\n` +
    fence("text", MCP_INSTRUCTIONS) +
    `\n\n## Tools\n\n` +
    doc.tools
      .map((t) => `### \`${t.name}\`\n\n${t.description}\n\n` + fence("json", JSON.stringify(t.inputSchema, null, 2)))
      .join("\n\n") +
    "\n",
);

const TOOL_DESCRIPTIONS = new Map(doc.tools.map((t) => [t.name, t.description]));
const EXTRA_DESCRIPTIONS: Record<string, string> = {
  close: "Close the view and release its browser process. Idempotent.",
  waitForIdle: "Wait until no network request has started for a quiet window. Chrome backend only.",
  scrollScan: TOOL_DESCRIPTIONS.get("scrollScan") ?? "",
  stressTest: TOOL_DESCRIPTIONS.get("stressTest") ?? "",
};

const privateNames = new Set(
  [...readFileSync(join(import.meta.dir, "..", "flamingo.ts"), "utf8")
    .matchAll(/\n\s+private\s+(?:readonly\s+|async\s+)*([a-zA-Z][a-zA-Z0-9]*)\s*[(<]/g)].map((m) => m[1]!),
);

const documented: Array<{ name: string; doc: string }> = [];
const missing: string[] = [];
for (const name of Object.getOwnPropertyNames(Engine.prototype).sort()) {
  if (name === "constructor" || privateNames.has(name)) continue;
  const descriptor = Object.getOwnPropertyDescriptor(Engine.prototype, name);
  if (!descriptor || typeof descriptor.value !== "function") continue;
  const text = TOOL_DESCRIPTIONS.get(name) ?? EXTRA_DESCRIPTIONS[name];
  if (text) documented.push({ name, doc: text.split(/(?<=\.)\s/)[0]!.trim() });
  else missing.push(name);
}

if (missing.length) console.warn(`  ! no description for: ${missing.join(", ")}`);

const OPTION_DOCS: Record<string, string> = {
  backend: '`"webkit"` (default, macOS, needs no browser install) or `"chrome"`, required for network interception and hover.',
  chromePath: "Chrome/Chromium/Brave executable. Defaults to `BUN_CHROME_PATH`, then a probe of standard locations.",
  width: "Viewport width in CSS pixels, normalised across both backends. Default `1280`.",
  height: "Viewport height in CSS pixels, normalised across both backends. Default `800`.",
  url: "Navigate here during `open()`.",
  bufferSize: "Maximum buffered console and network entries, oldest dropped. Default `500`.",
  onProgress: "`(stage, detail) => void`, called as long sweeps advance. Used for progress output.",
  profileDirectory: "Persist cookies and storage here to stay logged in between runs. Ephemeral by default.",
  evaluateTimeoutMs: "How long an in-page evaluate may stall before the view is rebuilt. Default `10000`.",
  reducedMotion: "Collapse CSS animations and transitions to zero duration so geometry is deterministic. Default `true`.",
};

const TYPE_DOCS: Record<string, string> = {
  EngineOptions: "Everything `Engine.open()` accepts.",
  Backend: '`"webkit"` or `"chrome"`.',
  InteractiveElement: "One actionable element: `ref`, `text`, viewport-space `center`, document-space position, and flags such as `pinned`, `nativePicker` and `leavesPage`.",
  InteractiveTree: "What `getInteractiveTree()` returns: the elements, plus counts of what was excluded and `blockedBy`.",
  Observation: "One step of the agent loop, including the `changed`, `newErrors` and `newFailedRequests` deltas.",
  ConsoleEntry: "A buffered console line: `type`, `text`, `timestamp`.",
  NetworkEntry: "A buffered request: `url`, `method`, `status`, `errorText`.",
  OverflowOffender: "An element sticking out past the viewport, with how far.",
  ResponsiveViolation: "One viewport that overflowed, with its worst offenders.",
};

const optionNames = (() => {
  const src = readFileSync(join(import.meta.dir, "..", "flamingo.ts"), "utf8");
  const start = src.indexOf("export interface EngineOptions {");
  const body = src.slice(start, src.indexOf("\n}", start));
  return [...body.matchAll(/^\s{2}(\w+)\??:/gm)].map((m) => m[1]!);
})();

const exportedTypes = (() => {
  const src = readFileSync(join(import.meta.dir, "..", "flamingo.ts"), "utf8");
  return [
    ...[...src.matchAll(/^export interface (\w+)/gm)].map((m) => m[1]!),
    ...[...src.matchAll(/^export type (\w+)/gm)].map((m) => m[1]!),
  ];
})();

const undocumentedOptions = optionNames.filter((n) => !OPTION_DOCS[n]);
const undocumentedTypes = exportedTypes.filter((n) => !TYPE_DOCS[n]);
if (undocumentedOptions.length) console.warn(`  ! undocumented options: ${undocumentedOptions.join(", ")}`);
if (undocumentedTypes.length) console.warn(`  ! undocumented types: ${undocumentedTypes.join(", ")}`);

const optionsTable =
  `\n\n## \`Engine.open(options)\`\n\n| Option | Meaning |\n| :-- | :-- |\n` +
  optionNames.map((n) => `| \`${n}\` | ${OPTION_DOCS[n] ?? ""} |`).join("\n");

const typesTable =
  `\n\n## Exported types\n\n| Type | Meaning |\n| :-- | :-- |\n` +
  exportedTypes.map((n) => `| \`${n}\` | ${TYPE_DOCS[n] ?? ""} |`).join("\n");

emit(
  "docs/api.md",
  GENERATED +
    `# Library API\n\n` +
    fence("ts", `import { Engine } from "tryflamingo";\n\nawait using e = await Engine.open({ url: "http://localhost:3000" });\nconst step = await e.observe();`) +
    `\n\n${documented.length} public methods on \`Engine\`. Full behaviour and options: [MCP tools](./mcp-tools.md), [internals](./internals.md).\n\n` +
    `| Method | What it does |\n| :-- | :-- |\n` +
    documented.map((m) => `| \`${m.name}\` | ${m.doc} |`).join("\n") +
    optionsTable +
    `\n\n## Also exported\n\n| Export | Purpose |\n| :-- | :-- |\n` +
    `| \`renderObservation(o)\` | Compact text form of an observation, ~74% fewer tokens than JSON |\n` +
    `| \`runMcpServer(opts)\` | Serve the MCP protocol on stdin/stdout |\n` +
    `| \`schemaDoc()\` | The machine-readable description of every command and tool |\n` +
    `| \`SKILL_MD\`, \`MCP_INSTRUCTIONS\` | The agent-facing guidance, as written by \`flamingo init\` |\n` +
    typesTable + "\n",
);

emit("skills/flamingo/SKILL.md", SKILL_MD);

emit(
  "mcp/config.json",
  JSON.stringify({ mcpServers: { flamingo: { command: "bunx", args: ["flamingo", "serve"] } } }, null, 2) + "\n",
);
emit("mcp/tools.json", JSON.stringify(doc, null, 2) + "\n");

if (check) {
  if (stale.length) {
    console.error(`\n\x1b[31mout of date:\x1b[0m\n${stale.map((p) => "  " + p).join("\n")}\n\nRun \`bun run docs\`.\n`);
    process.exit(1);
  }
  console.log("docs, skills and mcp are up to date");
} else {
  console.log("\ngenerated from flamingo.ts");
}
