#!/usr/bin/env bun

import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { Engine, SKILL_MD, MCP_INSTRUCTIONS, schemaDoc } from "../flamingo.ts";

const doc = schemaDoc();
const check = Bun.argv.includes("--check");
const stale: string[] = [];

function emit(path: string, body: string) {
  const full = join(import.meta.dir, "..", path);
  if (check) {
    if (!existsSync(full) || readFileSync(full, "utf8") !== body) stale.push(path);
    return;
  }
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body);
  console.log(`  ${path}`);
}

const GENERATED = "<!-- Generated by `bun run docs` from flamingo.ts. Do not edit by hand. -->\n\n";
const fence = (lang: string, body: string) => "```" + lang + "\n" + body + "\n```";

emit(
  "docs/cli.md",
  GENERATED +
    `# CLI reference\n\nflamingo ${doc.version} — ${doc.tagline}\n\n` +
    `## Commands\n\n| Command | Summary | Exit |\n| :-- | :-- | :-- |\n` +
    doc.commands.map((c) => `| \`${`flamingo ${c.name} ${c.args}`.trim()}\` | ${c.summary} | ${c.exits} |`).join("\n") +
    `\n\n` +
    doc.commands
      .map(
        (c) =>
          `## \`${`flamingo ${c.name} ${c.args}`.trim()}\`\n\n${c.summary}\n\n` +
          (c.flags.length ? `**Options:** ${c.flags.map((f) => `\`${f}\``).join(", ")}\n\n` : "") +
          `**Exit:** ${c.exits}\n\n` +
          fence("bash", c.examples.join("\n")),
      )
      .join("\n\n") +
    `\n\n## Exit codes\n\n| Code | Meaning |\n| :-- | :-- |\n` +
    Object.entries(doc.exitCodes).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n") +
    "\n",
);

emit(
  "docs/mcp-tools.md",
  GENERATED +
    `# MCP tools\n\n${doc.tools.length} tools, served over stdio JSON-RPC by \`flamingo serve\`.\n\n` +
    `Backends: default \`${doc.backends.default}\`. These need \`--backend chrome\`: ` +
    doc.backends.chromeOnly.map((t) => `\`${t}\``).join(", ") +
    `.\n\n## Server instructions\n\nSent to every client on \`initialize\`:\n\n` +
    fence("text", MCP_INSTRUCTIONS) +
    `\n\n## Tools\n\n` +
    doc.tools
      .map((t) => `### \`${t.name}\`\n\n${t.description}\n\n` + fence("json", JSON.stringify(t.inputSchema, null, 2)))
      .join("\n\n") +
    "\n",
);

const TOOL_DESCRIPTIONS = new Map(doc.tools.map((t) => [t.name, t.description]));
const EXTRA_DESCRIPTIONS: Record<string, string> = {
  close: "Close the view and release its browser process. Idempotent.",
  waitForIdle: "Wait until no network request has started for a quiet window. Chrome backend only.",
  scrollScan: TOOL_DESCRIPTIONS.get("scrollScan") ?? "",
  stressTest: TOOL_DESCRIPTIONS.get("stressTest") ?? "",
};

const privateNames = new Set(
  [...readFileSync(join(import.meta.dir, "..", "flamingo.ts"), "utf8")
    .matchAll(/\n\s+private\s+(?:readonly\s+|async\s+)*([a-zA-Z][a-zA-Z0-9]*)\s*[(<]/g)].map((m) => m[1]!),
);

const documented: Array<{ name: string; doc: string }> = [];
const missing: string[] = [];
for (const name of Object.getOwnPropertyNames(Engine.prototype).sort()) {
  if (name === "constructor" || privateNames.has(name)) continue;
  const descriptor = Object.getOwnPropertyDescriptor(Engine.prototype, name);
  if (!descriptor || typeof descriptor.value !== "function") continue;
  const text = TOOL_DESCRIPTIONS.get(name) ?? EXTRA_DESCRIPTIONS[name];
  if (text) documented.push({ name, doc: text.split(/(?<=\.)\s/)[0]!.trim() });
  else missing.push(name);
}

if (missing.length) console.warn(`  ! no description for: ${missing.join(", ")}`);

emit(
  "docs/api.md",
  GENERATED +
    `# Library API\n\n` +
    fence("ts", `import { Engine } from "@ayuxy027/flamingo";\n\nawait using e = await Engine.open({ url: "http://localhost:3000" });\nconst step = await e.observe();`) +
    `\n\n${documented.length} public methods on \`Engine\`. Full behaviour and options: [MCP tools](./mcp-tools.md), [internals](./internals.md).\n\n` +
    `| Method | What it does |\n| :-- | :-- |\n` +
    documented.map((m) => `| \`${m.name}\` | ${m.doc} |`).join("\n") +
    `\n\n## Also exported\n\n| Export | Purpose |\n| :-- | :-- |\n` +
    `| \`renderObservation(o)\` | Compact text form of an observation, ~74% fewer tokens than JSON |\n` +
    `| \`runMcpServer(opts)\` | Serve the MCP protocol on stdin/stdout |\n` +
    `| \`schemaDoc()\` | The machine-readable description of every command and tool |\n` +
    `| \`SKILL_MD\`, \`MCP_INSTRUCTIONS\` | The agent-facing guidance, as written by \`flamingo init\` |\n`,
);

emit("skills/flamingo/SKILL.md", SKILL_MD);

emit(
  "mcp/config.json",
  JSON.stringify({ mcpServers: { flamingo: { command: "bunx", args: ["flamingo", "serve"] } } }, null, 2) + "\n",
);
emit("mcp/tools.json", JSON.stringify(doc, null, 2) + "\n");

if (check) {
  if (stale.length) {
    console.error(`\n\x1b[31mout of date:\x1b[0m\n${stale.map((p) => "  " + p).join("\n")}\n\nRun \`bun run docs\`.\n`);
    process.exit(1);
  }
  console.log("docs, skills and mcp are up to date");
} else {
  console.log("\ngenerated from flamingo.ts");
}
